name: "backend-ci-cd"
on:
   push: 
     branches: [ "main" ]
     paths:
     - "backend/**"

jobs:
  deployment:
  
   runs-on: ubuntu-latest
   
   steps:
   - name: "Deploy to render"
     uses: johnbeynon/render-deploy-action@v0.0.8
     with:
          service-id: ${{ secrets.SERVICE_ID_BACKEND }}
          api-key: ${{ secrets.RENDER_API_KEY_BACKEND }}
