name: "backend-ci-cd"
on:
   push: 
     branches: [ "main" ]
     paths:
     - "backend/**"

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # checkout the repository

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4 

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Run tests
        run: bin/rake
  deployment:
  
   runs-on: ubuntu-latest
   needs: [testing]
   
   steps:
   - name: "Deploy to render"
     uses: johnbeynon/render-deploy-action@v0.0.8
     with:
          service-id: ${{ secrets.SERVICE_ID_BACKEND }}
          api-key: ${{ secrets.RENDER_API_KEY_BACKEND }}
